version: '3'
services:
  project-postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=codetest
      - POSTGRES_PASSWORD=codetest@123
      - POSTGRES_DB=codetest
  project-backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - project-postgres